// Code generated by codegen; DO NOT EDIT.

package ip2x

import "strconv"

//go:generate go run dbdata.go

// IP2Location™ IP Address Geolocation Database provides a solution to deduce
// the geolocation of a device connected to the Internet and to determine the
// approximate geographic location of an IP address along with some other useful
// information like country, region or state, city, latitude and longitude,
// ZIP/Postal code, time zone, Internet Service Provider (ISP) or company name,
// domain name, net speed, area code, weather station code, weather station
// name, mobile country code (MCC), mobile network code (MNC) and carrier brand,
// elevation, usage type, address type and advertising category.
// Up to DB25.
const IP2Location DBProduct = 1

// IP2Proxy™ Proxy Detection Database contains IP addresses which are used as VPN
// anonymizer, open proxies, web proxies and Tor exits, data center, web hosting
// (DCH) range, search engine robots (SES) and residential proxies (RES).
// Up to PX11.
const IP2Proxy DBProduct = 2

// IP address types as defined in Internet Protocol version 4 (IPv4) and
// Internet Protocol version 6 (IPv6).
//   - (A) Anycast - One to the closest
//   - (U) Unicast - One to one
//   - (M) Multicast - One to multiple
//   - (B) Broadcast - One to all
//
// In DB25.
const AddressType DBField = 1

// A varying length number assigned to geographic areas for call between cities.
//
// See https://www.ip2location.com/area-code-coverage.
//
// In DB15-16, DB18, DB20-22, DB24-25.
const AreaCode DBField = 2

// Autonomous system number (ASN).
//
// In PX7-11.
const AS DBField = 3

// Autonomous system (AS) name.
//
// In PX7-11.
const ASN DBField = 4

// The domain category is based on IAB Tech Lab Content Taxonomy.
//
// These categories are comprised of Tier-1 and Tier-2 (if available) level
// categories widely used in services like advertising, Internet security and
// filtering appliances.
//
// See https://www.ip2location.com/free/iab-categories.
//
// In DB25.
const Category DBField = 5

// City name.
//
// In DB3-25, PX3-11.
const City DBField = 6

// Two-character country code based on ISO 3166.
//
// In DB1-25, PX1-11.
const CountryCode DBField = 7

// Country name based on ISO 3166.
//
// In DB1-25, PX1-11.
const CountryName DBField = 8

// Internet domain name associated with IP address range.
//
// In DB7-8, DB10, DB12, DB14, DB16, DB18-20, DB22-25, PX5-11.
const Domain DBField = 9

// Average height of city above sea level in meters (m).
//
// In DB21-22, DB24-25.
const Elevation DBField = 10

// The IDD prefix to call the city from another country.
//
// In DB15-16, DB18, DB20-22, DB24-25.
const IDDCode DBField = 11

// Internet Service Provider or company's name.
//
// In DB2, DB4, DB6-8, DB10, DB12, DB14, DB16, DB18-20, DB22-25, PX4-11.
const ISP DBField = 12

// Proxy last seen in days.
//
// In PX8-11.
const LastSeen DBField = 13

// City latitude. Defaults to capital city latitude if city is unknown.
//
// In DB5-6, DB8-25.
const Latitude DBField = 14

// City longitude. Defaults to capital city longitude if city is unknown.
//
// In DB5-6, DB8-25.
const Longitude DBField = 15

// Mobile Country Codes (MCC) as defined in ITU E.212 for use in identifying
// mobile stations in wireless telephone networks, particularly GSM and UMTS
// networks.
//
// In DB19-20, DB22-25.
const MCC DBField = 16

// Mobile Network Code (MNC) is used in combination with a Mobile Country Code
// (MCC) to uniquely identify a mobile phone operator or carrier.
//
// In DB19-20, DB22-25.
const MNC DBField = 17

// Commercial brand associated with the mobile carrier.
//
// See https://www.ip2location.com/mobile-carrier-coverage.
//
// In DB19-20, DB22-25.
const MobileBrand DBField = 18

// Internet Connection Type
//   - (DIAL) dial up
//   - (DSL) broadband/cable/fiber/mobile
//   - (COMP) company/T1
//
// In DB13-14, DB16-18, DB20, DB22, DB24-25.
const NetSpeed DBField = 19

// Name of VPN provider if available.
//
// In PX11.
const Provider DBField = 20

// Type of proxy.
//   - (VPN) Anonymizing VPN services. These services offer users a publicly
//     accessible VPN for the purpose of hiding their IP address. Anonymity:
//     High.
//   - (TOR) Tor Exit Nodes. The Tor Project is an open network used by those
//     who wish to maintain anonymity. Anonymity: High.
//   - (DCH) Hosting Provider, Data Center or Content Delivery Network. Since
//     hosting providers and data centers can serve to provide anonymity, the
//     Anonymous IP database flags IP addresses associated with them. Anonymity:
//     Low.
//   - (PUB) Public Proxies. These are services which make connection requests
//     on a user's behalf. Proxy server software can be configured by the
//     administrator to listen on some specified port. These differ from VPNs in
//     that the proxies usually have limited functions compare to VPNs.
//     Anonymity: High.
//   - (WEB) Web Proxies. These are web services which make web requests on a
//     user's behalf. These differ from VPNs or Public Proxies in that they are
//     simple web-based proxies rather than operating at the IP address and
//     other ports level. Anonymity: High.
//   - (SES) Search Engine Robots. These are services which perform crawling or
//     scraping to a website, such as, the search engine spider or bots engine.
//     Anonymity: Low.
//   - (RES) Residential proxies. These services offer users proxy connections
//     through residential ISP with or without consents of peers to share their
//     idle resources. Only available with PX10 & PX11. Anonymity: Medium.
//
// In PX2-11.
const ProxyType DBField = 21

// Region or state name.
//
// In DB3-25, PX3-11.
const Region DBField = 22

// Security threat reported.
//   - (SPAM) Email and forum spammers
//   - (SCANNER) Network security scanners
//   - (BOTNET) Malware infected devices
//
// In PX9-11.
const Threat DBField = 23

// UTC time zone (with DST supported).
//
// In DB11-18, DB20-22, DB24-25.
const Timezone DBField = 24

// Usage type classification of ISP or company.
//   - (COM) Commercial
//   - (ORG) Organization
//   - (GOV) Government
//   - (MIL) Military
//   - (EDU) University/College/School
//   - (LIB) Library
//   - (CDN) Content Delivery Network
//   - (ISP) Fixed Line ISP
//   - (MOB) Mobile ISP
//   - (DCH) Data Center/Web Hosting/Transit
//   - (SES) Search Engine Spider
//   - (RSV) Reserved
//
// In DB23-25, PX6-11.
const UsageType DBField = 25

// The special code to identify the nearest weather observation station.
//
// In DB17-18, DB20, DB22, DB24-25.
const WeatherStationCode DBField = 26

// The name of the nearest weather observation station.
//
// In DB17-18, DB20, DB22, DB24-25.
const WeatherStationName DBField = 27

// ZIP code or Postal code.
//
// See https://www.ip2location.com/zip-code-coverage.
//
// In DB9-12, DB14-16, DB18, DB20-22, DB24-25.
const Zipcode DBField = 28

var _dbs = dbs{
	IP2Location: {
		1:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, dbField_columns: 2, dbField_dbs: dbI(IP2Location)<<8 | 1},
		2:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, ISP: dbI(dbtype_str) | 3<<4, dbField_columns: 3, dbField_dbs: dbI(IP2Location)<<8 | 2},
		3:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, dbField_columns: 4, dbField_dbs: dbI(IP2Location)<<8 | 3},
		4:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, ISP: dbI(dbtype_str) | 5<<4, dbField_columns: 5, dbField_dbs: dbI(IP2Location)<<8 | 4},
		5:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, dbField_columns: 6, dbField_dbs: dbI(IP2Location)<<8 | 5},
		6:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, ISP: dbI(dbtype_str) | 7<<4, dbField_columns: 7, dbField_dbs: dbI(IP2Location)<<8 | 6},
		7:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, ISP: dbI(dbtype_str) | 5<<4, Domain: dbI(dbtype_str) | 6<<4, dbField_columns: 6, dbField_dbs: dbI(IP2Location)<<8 | 7},
		8:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, ISP: dbI(dbtype_str) | 7<<4, Domain: dbI(dbtype_str) | 8<<4, dbField_columns: 8, dbField_dbs: dbI(IP2Location)<<8 | 8},
		9:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, dbField_columns: 7, dbField_dbs: dbI(IP2Location)<<8 | 9},
		10: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, ISP: dbI(dbtype_str) | 8<<4, Domain: dbI(dbtype_str) | 9<<4, dbField_columns: 9, dbField_dbs: dbI(IP2Location)<<8 | 10},
		11: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, dbField_columns: 8, dbField_dbs: dbI(IP2Location)<<8 | 11},
		12: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, dbField_columns: 10, dbField_dbs: dbI(IP2Location)<<8 | 12},
		13: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Timezone: dbI(dbtype_str) | 7<<4, NetSpeed: dbI(dbtype_str) | 8<<4, dbField_columns: 8, dbField_dbs: dbI(IP2Location)<<8 | 13},
		14: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, dbField_columns: 11, dbField_dbs: dbI(IP2Location)<<8 | 14},
		15: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, IDDCode: dbI(dbtype_str) | 9<<4, AreaCode: dbI(dbtype_str) | 10<<4, dbField_columns: 10, dbField_dbs: dbI(IP2Location)<<8 | 15},
		16: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, dbField_columns: 13, dbField_dbs: dbI(IP2Location)<<8 | 16},
		17: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Timezone: dbI(dbtype_str) | 7<<4, NetSpeed: dbI(dbtype_str) | 8<<4, WeatherStationCode: dbI(dbtype_str) | 9<<4, WeatherStationName: dbI(dbtype_str) | 10<<4, dbField_columns: 10, dbField_dbs: dbI(IP2Location)<<8 | 17},
		18: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, WeatherStationCode: dbI(dbtype_str) | 14<<4, WeatherStationName: dbI(dbtype_str) | 15<<4, dbField_columns: 15, dbField_dbs: dbI(IP2Location)<<8 | 18},
		19: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, ISP: dbI(dbtype_str) | 7<<4, Domain: dbI(dbtype_str) | 8<<4, MCC: dbI(dbtype_str) | 9<<4, MNC: dbI(dbtype_str) | 10<<4, MobileBrand: dbI(dbtype_str) | 11<<4, dbField_columns: 11, dbField_dbs: dbI(IP2Location)<<8 | 19},
		20: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, WeatherStationCode: dbI(dbtype_str) | 14<<4, WeatherStationName: dbI(dbtype_str) | 15<<4, MCC: dbI(dbtype_str) | 16<<4, MNC: dbI(dbtype_str) | 17<<4, MobileBrand: dbI(dbtype_str) | 18<<4, dbField_columns: 18, dbField_dbs: dbI(IP2Location)<<8 | 20},
		21: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, IDDCode: dbI(dbtype_str) | 9<<4, AreaCode: dbI(dbtype_str) | 10<<4, Elevation: dbI(dbtype_str) | 11<<4, dbField_columns: 11, dbField_dbs: dbI(IP2Location)<<8 | 21},
		22: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, WeatherStationCode: dbI(dbtype_str) | 14<<4, WeatherStationName: dbI(dbtype_str) | 15<<4, MCC: dbI(dbtype_str) | 16<<4, MNC: dbI(dbtype_str) | 17<<4, MobileBrand: dbI(dbtype_str) | 18<<4, Elevation: dbI(dbtype_str) | 19<<4, dbField_columns: 19, dbField_dbs: dbI(IP2Location)<<8 | 22},
		23: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, ISP: dbI(dbtype_str) | 7<<4, Domain: dbI(dbtype_str) | 8<<4, MCC: dbI(dbtype_str) | 9<<4, MNC: dbI(dbtype_str) | 10<<4, MobileBrand: dbI(dbtype_str) | 11<<4, UsageType: dbI(dbtype_str) | 12<<4, dbField_columns: 12, dbField_dbs: dbI(IP2Location)<<8 | 23},
		24: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, WeatherStationCode: dbI(dbtype_str) | 14<<4, WeatherStationName: dbI(dbtype_str) | 15<<4, MCC: dbI(dbtype_str) | 16<<4, MNC: dbI(dbtype_str) | 17<<4, MobileBrand: dbI(dbtype_str) | 18<<4, Elevation: dbI(dbtype_str) | 19<<4, UsageType: dbI(dbtype_str) | 20<<4, dbField_columns: 20, dbField_dbs: dbI(IP2Location)<<8 | 24},
		25: {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, Region: dbI(dbtype_str) | 3<<4, City: dbI(dbtype_str) | 4<<4, Latitude: dbI(dbtype_f32) | 255<<12 | 5<<4, Longitude: dbI(dbtype_f32) | 255<<12 | 6<<4, Zipcode: dbI(dbtype_str) | 7<<4, Timezone: dbI(dbtype_str) | 8<<4, ISP: dbI(dbtype_str) | 9<<4, Domain: dbI(dbtype_str) | 10<<4, NetSpeed: dbI(dbtype_str) | 11<<4, IDDCode: dbI(dbtype_str) | 12<<4, AreaCode: dbI(dbtype_str) | 13<<4, WeatherStationCode: dbI(dbtype_str) | 14<<4, WeatherStationName: dbI(dbtype_str) | 15<<4, MCC: dbI(dbtype_str) | 16<<4, MNC: dbI(dbtype_str) | 17<<4, MobileBrand: dbI(dbtype_str) | 18<<4, Elevation: dbI(dbtype_str) | 19<<4, UsageType: dbI(dbtype_str) | 20<<4, AddressType: dbI(dbtype_str) | 21<<4, Category: dbI(dbtype_str) | 22<<4, dbField_columns: 22, dbField_dbs: dbI(IP2Location)<<8 | 25},
	},
	IP2Proxy: {
		1:  {CountryCode: dbI(dbtype_str) | 2<<4, CountryName: dbI(dbtype_str) | 3<<12 | 2<<4, dbField_columns: 2, dbField_dbs: dbI(IP2Proxy)<<8 | 1},
		2:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, dbField_columns: 3, dbField_dbs: dbI(IP2Proxy)<<8 | 2},
		3:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, dbField_columns: 5, dbField_dbs: dbI(IP2Proxy)<<8 | 3},
		4:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, dbField_columns: 6, dbField_dbs: dbI(IP2Proxy)<<8 | 4},
		5:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, dbField_columns: 7, dbField_dbs: dbI(IP2Proxy)<<8 | 5},
		6:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, dbField_columns: 8, dbField_dbs: dbI(IP2Proxy)<<8 | 6},
		7:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, ASN: dbI(dbtype_str) | 9<<4, AS: dbI(dbtype_str) | 10<<4, dbField_columns: 10, dbField_dbs: dbI(IP2Proxy)<<8 | 7},
		8:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, ASN: dbI(dbtype_str) | 9<<4, AS: dbI(dbtype_str) | 10<<4, LastSeen: dbI(dbtype_str) | 11<<4, dbField_columns: 11, dbField_dbs: dbI(IP2Proxy)<<8 | 8},
		9:  {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, ASN: dbI(dbtype_str) | 9<<4, AS: dbI(dbtype_str) | 10<<4, LastSeen: dbI(dbtype_str) | 11<<4, Threat: dbI(dbtype_str) | 12<<4, dbField_columns: 12, dbField_dbs: dbI(IP2Proxy)<<8 | 9},
		10: {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, ASN: dbI(dbtype_str) | 9<<4, AS: dbI(dbtype_str) | 10<<4, LastSeen: dbI(dbtype_str) | 11<<4, Threat: dbI(dbtype_str) | 12<<4, dbField_columns: 12, dbField_dbs: dbI(IP2Proxy)<<8 | 10},
		11: {CountryCode: dbI(dbtype_str) | 3<<4, CountryName: dbI(dbtype_str) | 3<<12 | 3<<4, ProxyType: dbI(dbtype_str) | 2<<4, Region: dbI(dbtype_str) | 4<<4, City: dbI(dbtype_str) | 5<<4, ISP: dbI(dbtype_str) | 6<<4, Domain: dbI(dbtype_str) | 7<<4, UsageType: dbI(dbtype_str) | 8<<4, ASN: dbI(dbtype_str) | 9<<4, AS: dbI(dbtype_str) | 10<<4, LastSeen: dbI(dbtype_str) | 11<<4, Threat: dbI(dbtype_str) | 12<<4, Provider: dbI(dbtype_str) | 13<<4, dbField_columns: 13, dbField_dbs: dbI(IP2Proxy)<<8 | 11},
	},
}

const (
	dbProductMax    = DBProduct(2)
	dbTypeMax       = DBType(25)
	dbFieldMax      = DBField(28)
	dbField_columns = dbFieldMax + 1
	dbField_dbs     = dbFieldMax + 2
)

type dbI uint32
type dbS [dbFieldMax + 3]dbI
type dbs [dbProductMax + 1][dbTypeMax + 1]dbS

func dbinfo(p DBProduct, t DBType) *dbS {
	if p > dbProductMax || t > dbTypeMax {
		return nil
	}
	return &_dbs[p][t]
}

func (i dbS) Field(f DBField) dbI {
	if f > dbFieldMax {
		return 0
	}
	return i[f]
}

func (i dbS) Columns() uint8 {
	return uint8(i[dbField_columns])
}

func (i dbS) Info() (DBProduct, DBType) {
	x := i[dbField_dbs]
	return DBProduct(uint8(x >> 8)), DBType(uint8(x))
}

func (i dbS) AppendInfo(b []byte) []byte {
	p, t := i.Info()
	return strconv.AppendInt(append(append(append(b, p.product()...), ' '), p.prefix()...), int64(t), 10)
}

func (i dbS) AppendType(b []byte) []byte {
	p, t := i.Info()
	return strconv.AppendInt(append(b, p.prefix()...), int64(t), 10)
}

func (c dbI) IsValid() bool    { return c != 0 }
func (c dbI) Column() uint8    { return uint8(c >> 4) }
func (c dbI) IsPointer() bool  { return c&0xFF0 == 0 }
func (c dbI) PtrOffset() uint8 { return uint8(c >> 12) }
func (c dbI) Type() uint8      { return uint8(c & 0xF) }

func (p DBProduct) GoString() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_GoString[o]:_stringer_DBProduct_GoString[o+1]]
	}
	return "DBProduct(" + strconv.FormatUint(uint64(p), 10) + ")"
}

func (p DBProduct) product() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_product[o]:_stringer_DBProduct_product[o+1]]
	}
	return ""
}

func (p DBProduct) prefix() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_prefix[o]:_stringer_DBProduct_prefix[o+1]]
	}
	return ""
}

func (f DBField) GoString() string {
	if o := int64(f)*2 - 2; o >= 0 && o < 55 {
		return _stringer_xmjldxrr[_stringer_DBField_GoString[o]:_stringer_DBField_GoString[o+1]]
	}
	return "DBField(" + strconv.FormatUint(uint64(f), 10) + ")"
}

func (f DBField) column() string {
	if o := int64(f)*2 - 2; o >= 0 && o < 55 {
		return _stringer_xmjldxrr[_stringer_DBField_column[o]:_stringer_DBField_column[o+1]]
	}
	return ""
}

const _stringer_xmjldxrr = "IP2LocationIP2ProxyDBPXAddressTypeAreaCodeASNCategoryCityCountryCodeCountryNameDomainElevationIDDCodeISPLastSeenLatitudeLongitudeMCCMNCMobileBrandNetSpeedProviderProxyTypeRegionThreatTimezoneUsageTypeWeatherStationCodeWeatherStationNameZipcodeaddress_typearea_codeasncategorycitycountry_codecountry_namedomainelevationidd_codeisplast_seenlatitudelongitudemccmncmobile_brandnet_speedproviderproxy_typeregionthreattime_zoneusage_typeweather_station_codeweather_station_namezip_code" // ratio 479 / 502 = 0.9
var _stringer_DBProduct_GoString = [...]int{0, 11, 11, 19}
var _stringer_DBProduct_product = [...]int{0, 11, 11, 19}
var _stringer_DBProduct_prefix = [...]int{19, 21, 21, 23}
var _stringer_DBField_GoString = [...]int{23, 34, 34, 42, 42, 44, 42, 45, 45, 53, 53, 57, 57, 68, 68, 79, 79, 85, 85, 94, 94, 101, 101, 104, 104, 112, 112, 120, 120, 129, 129, 132, 132, 135, 135, 146, 146, 154, 154, 162, 162, 171, 171, 177, 177, 183, 183, 191, 191, 200, 200, 218, 218, 236, 236, 243}
var _stringer_DBField_column = [...]int{243, 255, 255, 264, 264, 266, 264, 267, 267, 275, 275, 279, 279, 291, 291, 303, 303, 309, 309, 318, 318, 326, 326, 329, 329, 338, 338, 346, 346, 355, 355, 358, 358, 361, 361, 373, 373, 382, 382, 390, 390, 400, 400, 406, 406, 412, 412, 421, 421, 431, 431, 451, 451, 471, 471, 479}
