// Code generated by codegen; DO NOT EDIT.

package ip2x

import "strconv"

//go:generate go run dbdata.go

// IP2Location™ IP Address Geolocation Database provides a solution to deduce
// the geolocation of a device connected to the Internet and to determine the
// approximate geographic location of an IP address along with some other useful
// information like country, region or state, city, latitude and longitude,
// ZIP/Postal code, time zone, Internet Service Provider (ISP) or company name,
// domain name, net speed, area code, weather station code, weather station
// name, mobile country code (MCC), mobile network code (MNC) and carrier brand,
// elevation, usage type, address type and advertising category.
//
// Up to DB25.
const IP2Location DBProduct = 1

// IP2Proxy™ Proxy Detection Database contains IP addresses which are used as VPN
// anonymizer, open proxies, web proxies and Tor exits, data center, web hosting
// (DCH) range, search engine robots (SES) and residential proxies (RES).
//
// Up to PX11.
const IP2Proxy DBProduct = 2

// IP address types as defined in Internet Protocol version 4 (IPv4) and
// Internet Protocol version 6 (IPv6).
//   - (A) Anycast - One to the closest
//   - (U) Unicast - One to one
//   - (M) Multicast - One to multiple
//   - (B) Broadcast - One to all
//
// In DB25.
const AddressType DBField = 1

// A varying length number assigned to geographic areas for call between cities.
//
// See https://www.ip2location.com/area-code-coverage.
//
// In DB15-16, DB18, DB20-22, DB24-25.
const AreaCode DBField = 2

// Autonomous system number (ASN).
//
// In PX7-11.
const AS DBField = 3

// Autonomous system (AS) name.
//
// In PX7-11.
const ASN DBField = 4

// The domain category is based on IAB Tech Lab Content Taxonomy.
//
// These categories are comprised of Tier-1 and Tier-2 (if available) level
// categories widely used in services like advertising, Internet security and
// filtering appliances.
//
// See https://www.ip2location.com/free/iab-categories.
//
// In DB25.
const Category DBField = 5

// City name.
//
// In DB3-25, PX3-11.
const City DBField = 6

// Two-character country code based on ISO 3166.
//
// In DB1-25, PX1-11.
const CountryCode DBField = 7

// Country name based on ISO 3166.
//
// In DB1-25, PX1-11.
const CountryName DBField = 8

// Internet domain name associated with IP address range.
//
// In DB7-8, DB10, DB12, DB14, DB16, DB18-20, DB22-25, PX5-11.
const Domain DBField = 9

// Average height of city above sea level in meters (m).
//
// In DB21-22, DB24-25.
const Elevation DBField = 10

// The IDD prefix to call the city from another country.
//
// In DB15-16, DB18, DB20-22, DB24-25.
const IDDCode DBField = 11

// Internet Service Provider or company's name.
//
// In DB2, DB4, DB6-8, DB10, DB12, DB14, DB16, DB18-20, DB22-25, PX4-11.
const ISP DBField = 12

// Proxy last seen in days.
//
// In PX8-11.
const LastSeen DBField = 13

// City latitude. Defaults to capital city latitude if city is unknown.
//
// In DB5-6, DB8-25.
const Latitude DBField = 14

// City longitude. Defaults to capital city longitude if city is unknown.
//
// In DB5-6, DB8-25.
const Longitude DBField = 15

// Mobile Country Codes (MCC) as defined in ITU E.212 for use in identifying
// mobile stations in wireless telephone networks, particularly GSM and UMTS
// networks.
//
// In DB19-20, DB22-25.
const MCC DBField = 16

// Mobile Network Code (MNC) is used in combination with a Mobile Country Code
// (MCC) to uniquely identify a mobile phone operator or carrier.
//
// In DB19-20, DB22-25.
const MNC DBField = 17

// Commercial brand associated with the mobile carrier.
//
// See https://www.ip2location.com/mobile-carrier-coverage.
//
// In DB19-20, DB22-25.
const MobileBrand DBField = 18

// Internet Connection Type
//   - (DIAL) dial up
//   - (DSL) broadband/cable/fiber/mobile
//   - (COMP) company/T1
//
// In DB13-14, DB16-18, DB20, DB22, DB24-25.
const NetSpeed DBField = 19

// Name of VPN provider if available.
//
// In PX11.
const Provider DBField = 20

// Type of proxy.
//   - (VPN) Anonymizing VPN services. These services offer users a publicly
//     accessible VPN for the purpose of hiding their IP address. Anonymity:
//     High.
//   - (TOR) Tor Exit Nodes. The Tor Project is an open network used by those
//     who wish to maintain anonymity. Anonymity: High.
//   - (DCH) Hosting Provider, Data Center or Content Delivery Network. Since
//     hosting providers and data centers can serve to provide anonymity, the
//     Anonymous IP database flags IP addresses associated with them. Anonymity:
//     Low.
//   - (PUB) Public Proxies. These are services which make connection requests
//     on a user's behalf. Proxy server software can be configured by the
//     administrator to listen on some specified port. These differ from VPNs in
//     that the proxies usually have limited functions compare to VPNs.
//     Anonymity: High.
//   - (WEB) Web Proxies. These are web services which make web requests on a
//     user's behalf. These differ from VPNs or Public Proxies in that they are
//     simple web-based proxies rather than operating at the IP address and
//     other ports level. Anonymity: High.
//   - (SES) Search Engine Robots. These are services which perform crawling or
//     scraping to a website, such as, the search engine spider or bots engine.
//     Anonymity: Low.
//   - (RES) Residential proxies. These services offer users proxy connections
//     through residential ISP with or without consents of peers to share their
//     idle resources. Only available with PX10 & PX11. Anonymity: Medium.
//
// In PX2-11.
const ProxyType DBField = 21

// Region or state name.
//
// In DB3-25, PX3-11.
const Region DBField = 22

// Security threat reported.
//   - (SPAM) Email and forum spammers
//   - (SCANNER) Network security scanners
//   - (BOTNET) Malware infected devices
//
// In PX9-11.
const Threat DBField = 23

// UTC time zone (with DST supported).
//
// In DB11-18, DB20-22, DB24-25.
const Timezone DBField = 24

// Usage type classification of ISP or company.
//   - (COM) Commercial
//   - (ORG) Organization
//   - (GOV) Government
//   - (MIL) Military
//   - (EDU) University/College/School
//   - (LIB) Library
//   - (CDN) Content Delivery Network
//   - (ISP) Fixed Line ISP
//   - (MOB) Mobile ISP
//   - (DCH) Data Center/Web Hosting/Transit
//   - (SES) Search Engine Spider
//   - (RSV) Reserved
//
// In DB23-25, PX6-11.
const UsageType DBField = 25

// The special code to identify the nearest weather observation station.
//
// In DB17-18, DB20, DB22, DB24-25.
const WeatherStationCode DBField = 26

// The name of the nearest weather observation station.
//
// In DB17-18, DB20, DB22, DB24-25.
const WeatherStationName DBField = 27

// ZIP code or Postal code.
//
// See https://www.ip2location.com/zip-code-coverage.
//
// In DB9-12, DB14-16, DB18, DB20-22, DB24-25.
const Zipcode DBField = 28

const (
	dbProductMax   = DBProduct(2)
	dbTypeMax      = DBType(25)
	dbFieldMax     = DBField(28)
	dbFieldColumns = dbFieldMax + 1
)

type dbft uint8

const (
	dbft_string dbft = 0
	dbft_f32le  dbft = 1
)

type dbfd uint32

func (d dbfd) IsValid() bool    { return d != 0 }
func (d dbfd) Column() uint32   { return uint32((^d >> 12) & 0xFF) }
func (d dbfd) PtrOffset() uint8 { return uint8((^d >> 4) & 0xFF) }
func (d dbfd) Type() dbft       { return dbft((^d >> 0) & 0xF) }

func getdbfd(p DBProduct, t DBType, f DBField) dbfd {
	if p > dbProductMax || t > dbTypeMax || f > dbFieldMax {
		return 0
	}
	return _dbfd[p][t][f]
}

func getdbcols(p DBProduct, t DBType) uint8 {
	if p > dbProductMax || t >= dbTypeMax {
		return 0
	}
	return uint8(_dbfd[p][t][dbFieldColumns])
}

var _dbfd = [dbProductMax + 1][dbTypeMax + 1][dbFieldMax + 2]dbfd{
	// ^|   FF   | column number (>1 since 1 is IPFrom)
	// ^|     FF | ptr offset, or direct if FF
	// ^|       F| storage type
	IP2Location: {
		1: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			dbFieldColumns: 2,
		},
		2: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			ISP:            ^dbfd(0x03000),
			dbFieldColumns: 3,
		},
		3: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			dbFieldColumns: 4,
		},
		4: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			ISP:            ^dbfd(0x05000),
			dbFieldColumns: 5,
		},
		5: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			dbFieldColumns: 6,
		},
		6: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x07000),
			dbFieldColumns: 7,
		},
		7: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			ISP:            ^dbfd(0x05000),
			Domain:         ^dbfd(0x06000),
			dbFieldColumns: 6,
		},
		8: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x07000),
			Domain:         ^dbfd(0x08000),
			dbFieldColumns: 8,
		},
		9: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			Zipcode:        ^dbfd(0x07000),
			dbFieldColumns: 7,
		},
		10: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x08000),
			Zipcode:        ^dbfd(0x07000),
			Domain:         ^dbfd(0x09000),
			dbFieldColumns: 9,
		},
		11: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			dbFieldColumns: 8,
		},
		12: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x09000),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			Domain:         ^dbfd(0x0A000),
			dbFieldColumns: 10,
		},
		13: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			Timezone:       ^dbfd(0x07000),
			NetSpeed:       ^dbfd(0x08000),
			dbFieldColumns: 8,
		},
		14: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x09000),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			Domain:         ^dbfd(0x0A000),
			NetSpeed:       ^dbfd(0x0B000),
			dbFieldColumns: 11,
		},
		15: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			IDDCode:        ^dbfd(0x09000),
			AreaCode:       ^dbfd(0x0A000),
			dbFieldColumns: 10,
		},
		16: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x09000),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			Domain:         ^dbfd(0x0A000),
			NetSpeed:       ^dbfd(0x0B000),
			IDDCode:        ^dbfd(0x0C000),
			AreaCode:       ^dbfd(0x0D000),
			dbFieldColumns: 13,
		},
		17: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			Timezone:           ^dbfd(0x07000),
			NetSpeed:           ^dbfd(0x08000),
			WeatherStationCode: ^dbfd(0x09000),
			WeatherStationName: ^dbfd(0x0A000),
			dbFieldColumns:     10,
		},
		18: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			ISP:                ^dbfd(0x09000),
			Zipcode:            ^dbfd(0x07000),
			Timezone:           ^dbfd(0x08000),
			Domain:             ^dbfd(0x0A000),
			NetSpeed:           ^dbfd(0x0B000),
			IDDCode:            ^dbfd(0x0C000),
			AreaCode:           ^dbfd(0x0D000),
			WeatherStationCode: ^dbfd(0x0E000),
			WeatherStationName: ^dbfd(0x0F000),
			dbFieldColumns:     15,
		},
		19: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x07000),
			Domain:         ^dbfd(0x08000),
			MCC:            ^dbfd(0x09000),
			MNC:            ^dbfd(0x0A000),
			MobileBrand:    ^dbfd(0x0B000),
			dbFieldColumns: 11,
		},
		20: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			ISP:                ^dbfd(0x09000),
			Zipcode:            ^dbfd(0x07000),
			Timezone:           ^dbfd(0x08000),
			Domain:             ^dbfd(0x0A000),
			NetSpeed:           ^dbfd(0x0B000),
			IDDCode:            ^dbfd(0x0C000),
			AreaCode:           ^dbfd(0x0D000),
			WeatherStationCode: ^dbfd(0x0E000),
			WeatherStationName: ^dbfd(0x0F000),
			MCC:                ^dbfd(0x10000),
			MNC:                ^dbfd(0x11000),
			MobileBrand:        ^dbfd(0x12000),
			dbFieldColumns:     18,
		},
		21: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			Zipcode:        ^dbfd(0x07000),
			Timezone:       ^dbfd(0x08000),
			IDDCode:        ^dbfd(0x09000),
			AreaCode:       ^dbfd(0x0A000),
			Elevation:      ^dbfd(0x0B000),
			dbFieldColumns: 11,
		},
		22: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			ISP:                ^dbfd(0x09000),
			Zipcode:            ^dbfd(0x07000),
			Timezone:           ^dbfd(0x08000),
			Domain:             ^dbfd(0x0A000),
			NetSpeed:           ^dbfd(0x0B000),
			IDDCode:            ^dbfd(0x0C000),
			AreaCode:           ^dbfd(0x0D000),
			WeatherStationCode: ^dbfd(0x0E000),
			WeatherStationName: ^dbfd(0x0F000),
			MCC:                ^dbfd(0x10000),
			MNC:                ^dbfd(0x11000),
			MobileBrand:        ^dbfd(0x12000),
			Elevation:          ^dbfd(0x13000),
			dbFieldColumns:     19,
		},
		23: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			Region:         ^dbfd(0x03000),
			City:           ^dbfd(0x04000),
			Latitude:       ^dbfd(0x05FF1),
			Longitude:      ^dbfd(0x06FF1),
			ISP:            ^dbfd(0x07000),
			Domain:         ^dbfd(0x08000),
			MCC:            ^dbfd(0x09000),
			MNC:            ^dbfd(0x0A000),
			MobileBrand:    ^dbfd(0x0B000),
			UsageType:      ^dbfd(0x0C000),
			dbFieldColumns: 12,
		},
		24: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			ISP:                ^dbfd(0x09000),
			Zipcode:            ^dbfd(0x07000),
			Timezone:           ^dbfd(0x08000),
			Domain:             ^dbfd(0x0A000),
			NetSpeed:           ^dbfd(0x0B000),
			IDDCode:            ^dbfd(0x0C000),
			AreaCode:           ^dbfd(0x0D000),
			WeatherStationCode: ^dbfd(0x0E000),
			WeatherStationName: ^dbfd(0x0F000),
			MCC:                ^dbfd(0x10000),
			MNC:                ^dbfd(0x11000),
			MobileBrand:        ^dbfd(0x12000),
			Elevation:          ^dbfd(0x13000),
			UsageType:          ^dbfd(0x14000),
			dbFieldColumns:     20,
		},
		25: {
			CountryCode:        ^dbfd(0x02000),
			CountryName:        ^dbfd(0x02030),
			Region:             ^dbfd(0x03000),
			City:               ^dbfd(0x04000),
			Latitude:           ^dbfd(0x05FF1),
			Longitude:          ^dbfd(0x06FF1),
			ISP:                ^dbfd(0x09000),
			Zipcode:            ^dbfd(0x07000),
			Timezone:           ^dbfd(0x08000),
			Domain:             ^dbfd(0x0A000),
			NetSpeed:           ^dbfd(0x0B000),
			IDDCode:            ^dbfd(0x0C000),
			AreaCode:           ^dbfd(0x0D000),
			WeatherStationCode: ^dbfd(0x0E000),
			WeatherStationName: ^dbfd(0x0F000),
			MCC:                ^dbfd(0x10000),
			MNC:                ^dbfd(0x11000),
			MobileBrand:        ^dbfd(0x12000),
			Elevation:          ^dbfd(0x13000),
			UsageType:          ^dbfd(0x14000),
			AddressType:        ^dbfd(0x15000),
			Category:           ^dbfd(0x16000),
			dbFieldColumns:     22,
		},
	},
	IP2Proxy: {
		1: {
			CountryCode:    ^dbfd(0x02000),
			CountryName:    ^dbfd(0x02030),
			dbFieldColumns: 2,
		},
		2: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			dbFieldColumns: 3,
		},
		3: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			dbFieldColumns: 5,
		},
		4: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			dbFieldColumns: 6,
		},
		5: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			dbFieldColumns: 7,
		},
		6: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			dbFieldColumns: 8,
		},
		7: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			ASN:            ^dbfd(0x09000),
			AS:             ^dbfd(0x0A000),
			dbFieldColumns: 10,
		},
		8: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			ASN:            ^dbfd(0x09000),
			AS:             ^dbfd(0x0A000),
			LastSeen:       ^dbfd(0x0B000),
			dbFieldColumns: 11,
		},
		9: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			ASN:            ^dbfd(0x09000),
			AS:             ^dbfd(0x0A000),
			LastSeen:       ^dbfd(0x0B000),
			Threat:         ^dbfd(0x0C000),
			dbFieldColumns: 12,
		},
		10: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			ASN:            ^dbfd(0x09000),
			AS:             ^dbfd(0x0A000),
			LastSeen:       ^dbfd(0x0B000),
			Threat:         ^dbfd(0x0C000),
			dbFieldColumns: 12,
		},
		11: {
			CountryCode:    ^dbfd(0x03000),
			CountryName:    ^dbfd(0x03030),
			ProxyType:      ^dbfd(0x02000),
			Region:         ^dbfd(0x04000),
			City:           ^dbfd(0x05000),
			ISP:            ^dbfd(0x06000),
			Domain:         ^dbfd(0x07000),
			UsageType:      ^dbfd(0x08000),
			ASN:            ^dbfd(0x09000),
			AS:             ^dbfd(0x0A000),
			LastSeen:       ^dbfd(0x0B000),
			Threat:         ^dbfd(0x0C000),
			Provider:       ^dbfd(0x0D000),
			dbFieldColumns: 13,
		},
	},
}

func (p DBProduct) GoString() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_GoString[o]:_stringer_DBProduct_GoString[o+1]]
	}
	return "DBProduct(" + strconv.FormatUint(uint64(p), 10) + ")"
}

func (p DBProduct) product() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_product[o]:_stringer_DBProduct_product[o+1]]
	}
	return ""
}

func (p DBProduct) prefix() string {
	if o := int64(p)*2 - 2; o >= 0 && o < 3 {
		return _stringer_xmjldxrr[_stringer_DBProduct_prefix[o]:_stringer_DBProduct_prefix[o+1]]
	}
	return ""
}

func (f DBField) GoString() string {
	if o := int64(f)*2 - 2; o >= 0 && o < 55 {
		return _stringer_xmjldxrr[_stringer_DBField_GoString[o]:_stringer_DBField_GoString[o+1]]
	}
	return "DBField(" + strconv.FormatUint(uint64(f), 10) + ")"
}

func (f DBField) column() string {
	if o := int64(f)*2 - 2; o >= 0 && o < 55 {
		return _stringer_xmjldxrr[_stringer_DBField_column[o]:_stringer_DBField_column[o+1]]
	}
	return ""
}

const _stringer_xmjldxrr = "IP2LocationIP2ProxyDBPXAddressTypeAreaCodeASNCategoryCityCountryCodeCountryNameDomainElevationIDDCodeISPLastSeenLatitudeLongitudeMCCMNCMobileBrandNetSpeedProviderProxyTypeRegionThreatTimezoneUsageTypeWeatherStationCodeWeatherStationNameZipcodeaddress_typearea_codeasncategorycitycountry_codecountry_namedomainelevationidd_codeisplast_seenlatitudelongitudemccmncmobile_brandnet_speedproviderproxy_typeregionthreattime_zoneusage_typeweather_station_codeweather_station_namezip_code" // ratio 479 / 502 = 0.9
var _stringer_DBProduct_GoString = [...]int{0, 11, 11, 19}
var _stringer_DBProduct_product = [...]int{0, 11, 11, 19}
var _stringer_DBProduct_prefix = [...]int{19, 21, 21, 23}
var _stringer_DBField_GoString = [...]int{23, 34, 34, 42, 42, 44, 42, 45, 45, 53, 53, 57, 57, 68, 68, 79, 79, 85, 85, 94, 94, 101, 101, 104, 104, 112, 112, 120, 120, 129, 129, 132, 132, 135, 135, 146, 146, 154, 154, 162, 162, 171, 171, 177, 177, 183, 183, 191, 191, 200, 200, 218, 218, 236, 236, 243}
var _stringer_DBField_column = [...]int{243, 255, 255, 264, 264, 266, 264, 267, 267, 275, 275, 279, 279, 291, 291, 303, 303, 309, 309, 318, 318, 326, 326, 329, 329, 338, 338, 346, 346, 355, 355, 358, 358, 361, 361, 373, 373, 382, 382, 390, 390, 400, 400, 406, 406, 412, 412, 421, 421, 431, 431, 451, 451, 471, 471, 479}
